### ISSUE TITLE
Doesn't find saves in subdirectories

### ISSUE THREAD

**Issue by mtwomey** [sharkusk/tts-mutility#2]
I organize my saves into folders, but tts-mutility only finds the saves in the root Saves/ directory.

**Comment by mtwomey** [comment]
Ok - this tool is really pretty awesome, good job.

I patched the subdirectory thing for my local use:
```
                for i, f in enumerate(
                    glob(os.path.join(base_dir, "**/*.json"), root_dir=root_dir, recursive = True)
                    # glob(os.path.join(base_dir, "*.json"), root_dir=root_dir)
                ):
                    if (
                        "WorkshopFileInfos" in f
                        or "SaveFileInfos" in f
                        or "TS_AutoSave" in f
                        # or "TS_Save" in f
                        or "Saved Objects" in f
                    ):
```

I also removed the exclusion of  names including "TS_Save" because a lot of times in my case, I want to back up a save I made in-game and those are named with "TS_Save".

A couple of suggestions would be:

1. Make the recursive change in general, I don't think is has any downsides and it will help when people organize their saves into folders
2. Allow command-line switch or in-interface toggle to include files named "TS_Save_*"

**Comment by sharkusk** [comment]
Thanks for the feedback. I added this as an option in commit 26736cf98519e9fb462b209939bd1eb1455962a0.  Check the config file after you update and run (config file is automatically updated when you run the app).

**Comment by mtwomey** [comment]
Awesome, what are your thoughts in general about scanning TS_Save* files? I'm curious how you're using this with respect to saves?

**Comment by sharkusk** [comment]
In general I only backup the original mod and assets. The actual save json files are backed up in the steam cloud. So, I didn't see much point in having multiple save listings/backups that contain identical assets.

That said, I'm okay with adding this as an option if you find it useful.

One thing to keep in mind is currently the backup names will clash (and overwrite each other) if you have the same filename in multiple save subdirectories. I should probably fix that if you need this feature.  :)

**Comment by sharkusk** [comment]
@mtwomey I added the option for TS_Save files here: e5d935ce769a918340033354584796194b2d2391

**Comment by mtwomey** [comment]
Thanks @sharkusk !

> One thing to keep in mind is currently the backup names will clash (and overwrite each other) if you have the same filename in multiple save subdirectories.

Yes, good point. I think it's manageable for now. I tend to customize mods to get them just as I like them and then they are in a "save". So I'm directly targeting specific saves for backup, so this works for me for now.
